language: python
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements/testing.txt -r requirements/production.txt --use-mirrors
  - python setup.py install
script:
  - python -m tls
  - python setup.py test
notifications:
    email: aaron.iles+travis-ci@gmail.com
